SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE
    AND P.DURATION_TYPE = '30일 이상'
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    -- WHERE 절에는 별칭(FEE)을 못 쓰므로 계산식을 그대로 복사해서 사용합니다.
    AND C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100) >= 500000
    AND C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100) < 2000000
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE ASC, 
    C.CAR_ID DESC;
