-- 코드를 입력하세요
SELECT
    A.YEAR,
    A.MONTH,
    A.GENDER,
    COUNT(DISTINCT A.USER_ID) AS USERS
FROM (
    SELECT
        YEAR(O.SALES_DATE) AS YEAR,
        MONTH(O.SALES_DATE) AS MONTH,
        U.GENDER AS GENDER,
        U.USER_ID
    FROM USER_INFO AS U
    JOIN ONLINE_SALE AS O
    ON U.USER_ID = O.USER_ID
        AND U.GENDER IS NOT NULL
) AS A
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER

