-- 코드를 입력하세요
SELECT
    A.APNT_NO AS APNT_NO,
    P.PT_NAME AS PT_NAME,
    P.PT_NO AS PT_NO,
    D.MCDP_CD AS MCDP_CD,
    D.DR_NAME AS DR_NAME,
    A.APNT_YMD
FROM
    APPOINTMENT AS A
LEFT JOIN
    PATIENT AS P
    ON A.PT_NO = P.PT_NO
LEFT JOIN DOCTOR D
    ON A.MDDR_ID = D.DR_ID
WHERE
    A.MCDP_CD = 'CS'
    AND DATE(A.APNT_YMD) = '2022-04-13'
    AND A.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC