-- 코드를 입력하세요
SELECT
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    RR.REVIEW_DATE

FROM
    MEMBER_PROFILE AS MP
JOIN
    REST_REVIEW AS RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC