-- 코드를 작성해주세요
SELECT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM
    DEVELOPERS AS D
LEFT JOIN
    SKILLCODES AS S
    ON D.SKILL_CODE = S.CODE
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY
    D.ID ASC