-- 코드를 입력하세요
SELECT
    DISTINCT CC.CAR_ID AS CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR AS CC
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
ON 
    CC.CAR_ID = CH.CAR_ID
WHERE MONTH(CH.START_DATE) = 10
AND CC.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC